services:
  - postgresql
rvm:
  - 2.2.3
before_script:
  - psql -c 'create database workshops_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
addons:
  postgresql: '9.3'
script: RAILS_ENV=test bundle exec rspec
